const mongoose = require("mongoose");
const { Affiliate } = require("./models/AffiliateSchema");
const { Product } = require("./models/ProductSchema");

mongoose.connect(
  "mongodb+srv://manicharan12:adminReports@cluster0.fbsrz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  }
);

const affiliateData = [
  {
    affiliate: "Affiliate X",
    date: "2024-08-01",
    linksShared: 10,
    occupation: "Student",
    productsMarketed: ["Product A", "Product B"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-03",
    linksShared: 12,
    occupation: "Student",
    productsMarketed: ["Product A", "Product C"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-05",
    linksShared: 14,
    occupation: "Professional",
    productsMarketed: ["Product D", "Product E"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-07",
    linksShared: 16,
    occupation: "Professional",
    productsMarketed: ["Product F", "Product G"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-09",
    linksShared: 18,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product H", "Product I"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-11",
    linksShared: 17,
    occupation: "Marketing Agent",
    productsMarketed: ["Product J", "Product K"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-13",
    linksShared: 15,
    occupation: "Teacher",
    productsMarketed: ["Product L", "Product M"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-15",
    linksShared: 16,
    occupation: "Placement Officer",
    productsMarketed: ["Product N", "Product O"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-17",
    linksShared: 18,
    occupation: "Other",
    productsMarketed: ["Product P", "Product Q"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-02",
    linksShared: 15,
    occupation: "Professional",
    productsMarketed: ["Product R", "Product S"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-04",
    linksShared: 17,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product T", "Product U"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-06",
    linksShared: 19,
    occupation: "Marketing Agent",
    productsMarketed: ["Product V", "Product W"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-08",
    linksShared: 21,
    occupation: "Teacher",
    productsMarketed: ["Product X", "Product Y"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-10",
    linksShared: 23,
    occupation: "Placement Officer",
    productsMarketed: ["Product Z", "Product A1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-12",
    linksShared: 22,
    occupation: "Other",
    productsMarketed: ["Product B1", "Product C1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-14",
    linksShared: 20,
    occupation: "Student",
    productsMarketed: ["Product D1", "Product E1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-16",
    linksShared: 21,
    occupation: "Professional",
    productsMarketed: ["Product F1", "Product G1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-18",
    linksShared: 23,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product H1", "Product I1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-03",
    linksShared: 8,
    occupation: "Marketing Agent",
    productsMarketed: ["Product J1", "Product K1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-05",
    linksShared: 9,
    occupation: "Teacher",
    productsMarketed: ["Product L1", "Product M1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-07",
    linksShared: 10,
    occupation: "Placement Officer",
    productsMarketed: ["Product N1", "Product O1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-09",
    linksShared: 11,
    occupation: "Other",
    productsMarketed: ["Product P1", "Product Q1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-11",
    linksShared: 10,
    occupation: "Student",
    productsMarketed: ["Product R1", "Product S1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-13",
    linksShared: 9,
    occupation: "Professional",
    productsMarketed: ["Product T1", "Product U1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-15",
    linksShared: 10,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product V1", "Product W1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-17",
    linksShared: 11,
    occupation: "Marketing Agent",
    productsMarketed: ["Product X1", "Product Y1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-19",
    linksShared: 12,
    occupation: "Teacher",
    productsMarketed: ["Product Z1", "Product A2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-04",
    linksShared: 20,
    occupation: "Placement Officer",
    productsMarketed: ["Product B2", "Product C2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-06",
    linksShared: 22,
    occupation: "Other",
    productsMarketed: ["Product D2", "Product E2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-08",
    linksShared: 24,
    occupation: "Student",
    productsMarketed: ["Product F2", "Product G2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-10",
    linksShared: 26,
    occupation: "Professional",
    productsMarketed: ["Product H2", "Product I2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-12",
    linksShared: 25,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product J2", "Product K2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-14",
    linksShared: 23,
    occupation: "Marketing Agent",
    productsMarketed: ["Product L2", "Product M2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-16",
    linksShared: 24,
    occupation: "Teacher",
    productsMarketed: ["Product N2", "Product O2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-18",
    linksShared: 26,
    occupation: "Placement Officer",
    productsMarketed: ["Product P2", "Product Q2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-20",
    linksShared: 28,
    occupation: "Other",
    productsMarketed: ["Product R2", "Product S2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-05",
    linksShared: 5,
    occupation: "Student",
    productsMarketed: ["Product T2", "Product U2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-07",
    linksShared: 6,
    occupation: "Professional",
    productsMarketed: ["Product V2", "Product W2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-09",
    linksShared: 7,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product X2", "Product Y2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-11",
    linksShared: 8,
    occupation: "Marketing Agent",
    productsMarketed: ["Product Z2", "Product A3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-13",
    linksShared: 7,
    occupation: "Teacher",
    productsMarketed: ["Product B3", "Product C3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-15",
    linksShared: 6,
    occupation: "Placement Officer",
    productsMarketed: ["Product D3", "Product E3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-17",
    linksShared: 7,
    occupation: "Other",
    productsMarketed: ["Product F3", "Product G3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-19",
    linksShared: 8,
    occupation: "Student",
    productsMarketed: ["Product H3", "Product I3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-21",
    linksShared: 9,
    occupation: "Professional",
    productsMarketed: ["Product J3", "Product K3"],
  },
];

const productData = [
  {
    product: "Product A",
    date: "2024-08-01",
    clicks: 120,
    conversions: 30,
    revenue: 1500,
  },
  {
    product: "Product A",
    date: "2024-08-03",
    clicks: 130,
    conversions: 32,
    revenue: 1600,
  },
  {
    product: "Product A",
    date: "2024-08-05",
    clicks: 140,
    conversions: 35,
    revenue: 1700,
  },
  {
    product: "Product A",
    date: "2024-08-07",
    clicks: 150,
    conversions: 37,
    revenue: 1800,
  },
  {
    product: "Product A",
    date: "2024-08-09",
    clicks: 160,
    conversions: 40,
    revenue: 1900,
  },
  {
    product: "Product A",
    date: "2024-08-11",
    clicks: 155,
    conversions: 38,
    revenue: 1850,
  },
  {
    product: "Product A",
    date: "2024-08-13",
    clicks: 145,
    conversions: 36,
    revenue: 1750,
  },
  {
    product: "Product A",
    date: "2024-08-15",
    clicks: 150,
    conversions: 37,
    revenue: 1800,
  },
  {
    product: "Product A",
    date: "2024-08-17",
    clicks: 160,
    conversions: 39,
    revenue: 1900,
  },
  {
    product: "Product B",
    date: "2024-08-02",
    clicks: 200,
    conversions: 50,
    revenue: 3000,
  },
  {
    product: "Product B",
    date: "2024-08-04",
    clicks: 210,
    conversions: 53,
    revenue: 3150,
  },
  {
    product: "Product B",
    date: "2024-08-06",
    clicks: 220,
    conversions: 55,
    revenue: 3300,
  },
  {
    product: "Product B",
    date: "2024-08-08",
    clicks: 230,
    conversions: 57,
    revenue: 3450,
  },
  {
    product: "Product B",
    date: "2024-08-10",
    clicks: 240,
    conversions: 60,
    revenue: 3600,
  },
  {
    product: "Product B",
    date: "2024-08-12",
    clicks: 235,
    conversions: 58,
    revenue: 3520,
  },
  {
    product: "Product B",
    date: "2024-08-14",
    clicks: 225,
    conversions: 55,
    revenue: 3375,
  },
  {
    product: "Product B",
    date: "2024-08-16",
    clicks: 220,
    conversions: 54,
    revenue: 3300,
  },
  {
    product: "Product B",
    date: "2024-08-18",
    clicks: 230,
    conversions: 56,
    revenue: 3450,
  },
  {
    product: "Product C",
    date: "2024-08-03",
    clicks: 100,
    conversions: 20,
    revenue: 1000,
  },
  {
    product: "Product C",
    date: "2024-08-05",
    clicks: 110,
    conversions: 22,
    revenue: 1100,
  },
  {
    product: "Product C",
    date: "2024-08-07",
    clicks: 120,
    conversions: 24,
    revenue: 1200,
  },
  {
    product: "Product C",
    date: "2024-08-09",
    clicks: 130,
    conversions: 26,
    revenue: 1300,
  },
  {
    product: "Product C",
    date: "2024-08-11",
    clicks: 125,
    conversions: 25,
    revenue: 1250,
  },
  {
    product: "Product C",
    date: "2024-08-13",
    clicks: 115,
    conversions: 23,
    revenue: 1150,
  },
  {
    product: "Product C",
    date: "2024-08-15",
    clicks: 120,
    conversions: 24,
    revenue: 1200,
  },
  {
    product: "Product C",
    date: "2024-08-17",
    clicks: 130,
    conversions: 26,
    revenue: 1300,
  },
  {
    product: "Product C",
    date: "2024-08-19",
    clicks: 140,
    conversions: 28,
    revenue: 1400,
  },
  {
    product: "Product D",
    date: "2024-08-04",
    clicks: 150,
    conversions: 30,
    revenue: 1500,
  },
  {
    product: "Product D",
    date: "2024-08-06",
    clicks: 160,
    conversions: 32,
    revenue: 1600,
  },
  {
    product: "Product D",
    date: "2024-08-08",
    clicks: 170,
    conversions: 34,
    revenue: 1700,
  },
  {
    product: "Product D",
    date: "2024-08-10",
    clicks: 180,
    conversions: 36,
    revenue: 1800,
  },
  {
    product: "Product D",
    date: "2024-08-12",
    clicks: 175,
    conversions: 35,
    revenue: 1750,
  },
  {
    product: "Product D",
    date: "2024-08-14",
    clicks: 165,
    conversions: 33,
    revenue: 1650,
  },
  {
    product: "Product D",
    date: "2024-08-16",
    clicks: 170,
    conversions: 34,
    revenue: 1700,
  },
  {
    product: "Product D",
    date: "2024-08-18",
    clicks: 180,
    conversions: 36,
    revenue: 1800,
  },
  {
    product: "Product D",
    date: "2024-08-20",
    clicks: 190,
    conversions: 38,
    revenue: 1900,
  },
  {
    product: "Product E",
    date: "2024-08-05",
    clicks: 175,
    conversions: 45,
    revenue: 2500,
  },
  {
    product: "Product E",
    date: "2024-08-07",
    clicks: 185,
    conversions: 48,
    revenue: 2600,
  },
  {
    product: "Product E",
    date: "2024-08-09",
    clicks: 195,
    conversions: 50,
    revenue: 2700,
  },
  {
    product: "Product E",
    date: "2024-08-11",
    clicks: 205,
    conversions: 52,
    revenue: 2800,
  },
  {
    product: "Product E",
    date: "2024-08-13",
    clicks: 200,
    conversions: 51,
    revenue: 2750,
  },
  {
    product: "Product E",
    date: "2024-08-15",
    clicks: 190,
    conversions: 49,
    revenue: 2650,
  },
  {
    product: "Product E",
    date: "2024-08-17",
    clicks: 195,
    conversions: 50,
    revenue: 2700,
  },
  {
    product: "Product E",
    date: "2024-08-19",
    clicks: 205,
    conversions: 52,
    revenue: 2800,
  },
  {
    product: "Product E",
    date: "2024-08-21",
    clicks: 215,
    conversions: 54,
    revenue: 2900,
  },
];

async function insertDummyData() {
  try {
    await Affiliate.deleteMany({});
    await Product.deleteMany({});

    await Affiliate.insertMany(affiliateData);
    await Product.insertMany(productData);

    console.log("Dummy data inserted successfully");
    process.exit(0);
  } catch (error) {
    console.error("Error inserting dummy data:", error);
    process.exit(1);
  }
}

insertDummyData();
